const Brand = require('../models/Brand');
const fs = require('fs');
const path = require('path');

// Helper to clean up local disk files
const deleteLocalFile = (filePath) => {
  if (filePath && filePath.startsWith('/uploads/')) {
    const fullPath = path.join(__dirname, '../public', filePath);
    if (fs.existsSync(fullPath)) {
      fs.unlink(fullPath, (err) => {
        if (err) console.error(`Failed to delete file: ${fullPath}`, err);
      });
    }
  }
};

// GET ALL BRANDS
const getBrands = async (req, res) => {
  try {
    const { search, status, sort, page = 1, limit = 6 } = req.query;

    const query = {};
    if (search) query.name = { $regex: search, $options: 'i' };
    if (status && status !== 'All') query.status = status;

    let sortOptions = { name: sort === 'Z to A' ? -1 : 1 };

    const pageNum = parseInt(page, 10) || 1;
    const limitNum = parseInt(limit, 10) || 6;
    const skip = (pageNum - 1) * limitNum;

    const totalBrands = await Brand.countDocuments();
    const activeBrands = await Brand.countDocuments({ status: 'Active' });
    const filteredTotal = await Brand.countDocuments(query);

    const brands = await Brand.find(query)
      .sort(sortOptions)
      .skip(skip)
      .limit(limitNum);

    res.status(200).json({
      success: true,
      stats: { totalBrands, activeBrands },
      pagination: {
        totalItems: filteredTotal,
        totalPages: Math.ceil(filteredTotal / limitNum) || 1,
        currentPage: pageNum,
        limit: limitNum,
      },
      count: brands.length,
      data: brands,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// GET SINGLE BRAND
const getBrandById = async (req, res) => {
  try {
    const brand = await Brand.findById(req.params.id);
    if (!brand) return res.status(404).json({ success: false, message: 'Brand not found' });
    res.status(200).json({ success: true, data: brand });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// CREATE BRAND
const createBrand = async (req, res) => {
  try {
    const {
      name, slug, category, description, website,
      status, featured, seoTitle, metaDesc, displayOrder,
    } = req.body;

    if (!name || !name.trim()) {
      return res.status(400).json({ success: false, message: 'Brand name is required' });
    }

    let imageUrl = 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=200&auto=format&fit=crop';

    // ✅ FIXED: Read path generated by convertToWebp middleware (/uploads/brands/brand-xxx.webp)
    if (req.file) {
      imageUrl = req.file.path || req.file.destinationPath || `/uploads/brands/${req.file.filename}`;
    }

    const newBrand = new Brand({
      name: name.trim(),
      slug: slug ? slug.trim() : undefined,
      category: category || 'Chocolates',
      description: description || 'No description provided',
      website: website || '',
      status: status || 'Active',
      featured: featured === 'true' || featured === true,
      seoTitle: seoTitle || '',
      metaDesc: metaDesc || '',
      displayOrder: Number(displayOrder) || 1,
      image: imageUrl,
    });

    const savedBrand = await newBrand.save();

    res.status(201).json({
      success: true,
      message: 'Brand created successfully',
      data: savedBrand,
    });
  } catch (error) {
    if (req.file && (req.file.path || req.file.filename)) {
      deleteLocalFile(req.file.path || `/uploads/brands/${req.file.filename}`);
    }
    res.status(400).json({ success: false, message: error.message });
  }
};

// UPDATE BRAND
const updateBrand = async (req, res) => {
  try {
    const brand = await Brand.findById(req.params.id);

    if (!brand) {
      if (req.file) deleteLocalFile(req.file.path || `/uploads/brands/${req.file.filename}`);
      return res.status(404).json({ success: false, message: 'Brand not found' });
    }

    const {
      name, slug, category, description, website,
      status, featured, seoTitle, metaDesc, displayOrder,
    } = req.body;

    if (name) brand.name = name.trim();
    if (slug) brand.slug = slug.trim();
    if (category) brand.category = category;
    if (description !== undefined) brand.description = description;
    if (website !== undefined) brand.website = website;
    if (status) brand.status = status;
    if (featured !== undefined) brand.featured = featured === 'true' || featured === true;
    if (seoTitle !== undefined) brand.seoTitle = seoTitle;
    if (metaDesc !== undefined) brand.metaDesc = metaDesc;
    if (displayOrder !== undefined) brand.displayOrder = Number(displayOrder);

    if (req.file) {
      deleteLocalFile(brand.image);
      brand.image = req.file.path || req.file.destinationPath || `/uploads/brands/${req.file.filename}`;
    }

    const updatedBrand = await brand.save();

    res.status(200).json({
      success: true,
      message: 'Brand updated successfully',
      data: updatedBrand,
    });
  } catch (error) {
    if (req.file) deleteLocalFile(req.file.path || `/uploads/brands/${req.file.filename}`);
    res.status(400).json({ success: false, message: error.message });
  }
};

// TOGGLE STATUS
const toggleBrandStatus = async (req, res) => {
  try {
    const brand = await Brand.findById(req.params.id);
    if (!brand) return res.status(404).json({ success: false, message: 'Brand not found' });

    brand.status = brand.status === 'Active' ? 'Inactive' : 'Active';
    await brand.save();

    res.status(200).json({
      success: true,
      message: `Brand status updated to ${brand.status}`,
      data: brand,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// DELETE BRAND
const deleteBrand = async (req, res) => {
  try {
    const brand = await Brand.findById(req.params.id);
    if (!brand) return res.status(404).json({ success: false, message: 'Brand not found' });

    deleteLocalFile(brand.image);
    await brand.deleteOne();

    res.status(200).json({ success: true, message: 'Brand deleted successfully' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

module.exports = {
  getBrands,
  getBrandById,
  createBrand,
  updateBrand,
  toggleBrandStatus,
  deleteBrand,
};